# Site settings
title: 'Charles Villard' # Your Title
tagline: 'Web Developer from Miami, FL' # A brief tagline for your site
sidebar_image: /images/cover1.jpg

# Build settings
markdown: kramdown
highlighter: rouge
baseurl:  # the subpath of your site, e.g. /blog/
